/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProyectoUVG;

import javax.swing.JFrame;

/**
 *
 * @author evely
 */
public class Ingreso extends javax.swing.JFrame {

    /**
     * Creates new form Ingreso
     */
    public Ingreso() {
        initComponents();
        setResizable(false); // Desactiva el redimensionamiento
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Registro = new javax.swing.JPanel();
        RegistroG1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        RegistroG2 = new javax.swing.JButton();
        RegistroG3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Registro.setBackground(new java.awt.Color(0, 102, 102));
        Registro.setLayout(null);

        RegistroG1.setBackground(new java.awt.Color(51, 255, 51));
        RegistroG1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        RegistroG1.setText("Registrarse");
        RegistroG1.setMaximumSize(new java.awt.Dimension(103, 33));
        RegistroG1.setPreferredSize(new java.awt.Dimension(103, 33));
        RegistroG1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistroG1MouseClicked(evt);
            }
        });
        RegistroG1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroG1ActionPerformed(evt);
            }
        });
        Registro.add(RegistroG1);
        RegistroG1.setBounds(220, 420, 180, 42);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("FITNESS&HOUSE");
        Registro.add(jLabel1);
        jLabel1.setBounds(170, 10, 160, 30);

        RegistroG2.setBackground(new java.awt.Color(51, 255, 51));
        RegistroG2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        RegistroG2.setText("Iniciar sesion");
        RegistroG2.setMaximumSize(new java.awt.Dimension(103, 33));
        RegistroG2.setPreferredSize(new java.awt.Dimension(103, 33));
        RegistroG2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistroG2MouseClicked(evt);
            }
        });
        RegistroG2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroG2ActionPerformed(evt);
            }
        });
        Registro.add(RegistroG2);
        RegistroG2.setBounds(200, 340, 150, 42);

        RegistroG3.setBackground(new java.awt.Color(51, 255, 51));
        RegistroG3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        RegistroG3.setText("Registrarse con Gmail");
        RegistroG3.setMaximumSize(new java.awt.Dimension(103, 33));
        RegistroG3.setPreferredSize(new java.awt.Dimension(103, 33));
        RegistroG3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistroG3MouseClicked(evt);
            }
        });
        RegistroG3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroG3ActionPerformed(evt);
            }
        });
        Registro.add(RegistroG3);
        RegistroG3.setBounds(190, 510, 244, 42);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Registro.add(jButton1);
        jButton1.setBounds(380, 20, 90, 32);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProyectoUVG/gym4.jpg"))); // NOI18N
        Registro.add(jLabel2);
        jLabel2.setBounds(0, -50, 200, 210);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Registro, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Registro, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE)
        );

        Registro.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistroG1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistroG1MouseClicked

    }//GEN-LAST:event_RegistroG1MouseClicked

    private void RegistroG1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroG1ActionPerformed
        usuario user = new usuario();
        user.setVisible(true);
    }//GEN-LAST:event_RegistroG1ActionPerformed

    private void RegistroG2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistroG2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistroG2MouseClicked

    private void RegistroG2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroG2ActionPerformed
            usuario user = new usuario();
        user.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistroG2ActionPerformed

    private void RegistroG3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistroG3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistroG3MouseClicked

    private void RegistroG3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroG3ActionPerformed
                usuario user = new usuario();
        user.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistroG3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

      Vista1 atras = new Vista1();
      atras.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ingreso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Registro;
    private javax.swing.JButton RegistroG1;
    private javax.swing.JButton RegistroG2;
    private javax.swing.JButton RegistroG3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
