/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProyectoUVG;

import java.awt.Toolkit;
import javax.swing.JFrame;



/**
 *
 * @author evely
 */
public class VistaE extends javax.swing.JFrame {

    /**
     * Creates new form VistaE
     */
    public VistaE() {
        
        initComponents();
        
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registro = new javax.swing.JPanel();
        Inicio = new javax.swing.JButton();
        RegistroG = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        atras = new javax.swing.JButton();
        Registrarse1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 100));

        registro.setBackground(new java.awt.Color(0, 102, 102));
        registro.setLayout(null);

        Inicio.setBackground(new java.awt.Color(51, 255, 51));
        Inicio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Inicio.setText("Iniciar sesion");
        Inicio.setMaximumSize(new java.awt.Dimension(103, 33));
        Inicio.setPreferredSize(new java.awt.Dimension(103, 33));
        Inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InicioMouseClicked(evt);
            }
        });
        Inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioActionPerformed(evt);
            }
        });
        registro.add(Inicio);
        Inicio.setBounds(590, 320, 170, 42);

        RegistroG.setBackground(new java.awt.Color(51, 255, 51));
        RegistroG.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        RegistroG.setText("Registrar con Gmail");
        RegistroG.setMaximumSize(new java.awt.Dimension(103, 33));
        RegistroG.setPreferredSize(new java.awt.Dimension(103, 33));
        RegistroG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistroGMouseClicked(evt);
            }
        });
        registro.add(RegistroG);
        RegistroG.setBounds(560, 480, 244, 42);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("FITNESS&HOUSE");
        registro.add(jLabel1);
        jLabel1.setBounds(560, 20, 240, 110);

        atras.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        atras.setText("Atras");
        atras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atrasMouseClicked(evt);
            }
        });
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });
        registro.add(atras);
        atras.setBounds(10, 10, 140, 32);

        Registrarse1.setBackground(new java.awt.Color(51, 255, 51));
        Registrarse1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Registrarse1.setText("Registrarse");
        Registrarse1.setMaximumSize(new java.awt.Dimension(103, 33));
        Registrarse1.setPreferredSize(new java.awt.Dimension(103, 33));
        Registrarse1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Registrarse1MouseClicked(evt);
            }
        });
        Registrarse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Registrarse1ActionPerformed(evt);
            }
        });
        registro.add(Registrarse1);
        Registrarse1.setBounds(590, 400, 170, 42);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(registro, javax.swing.GroupLayout.PREFERRED_SIZE, 1374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registro, javax.swing.GroupLayout.DEFAULT_SIZE, 767, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InicioMouseClicked
       usuario registrar = new usuario();
       registrar.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_InicioMouseClicked

    private void RegistroGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistroGMouseClicked
        
    }//GEN-LAST:event_RegistroGMouseClicked

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
     Vista1 inicio = new Vista1();        // TODO add your handling code here:
        inicio.setVisible(true);
    }//GEN-LAST:event_atrasActionPerformed

    private void atrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasMouseClicked
       

        this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_atrasMouseClicked

    private void InicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioActionPerformed
    
// TODO add your handling code here:
  
    }//GEN-LAST:event_InicioActionPerformed

    private void Registrarse1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Registrarse1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Registrarse1MouseClicked

    private void Registrarse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Registrarse1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Registrarse1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Inicio;
    private javax.swing.JButton Registrarse1;
    private javax.swing.JButton RegistroG;
    private javax.swing.JButton atras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel registro;
    // End of variables declaration//GEN-END:variables
}
