/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProyectoUVG;

import java.awt.Toolkit;
import javax.swing.JFrame;



/**
 *
 * @author evely
 */
public class VistaE extends javax.swing.JFrame {

    /**
     * Creates new form VistaE
     */
    public VistaE() {
        
        initComponents();
        
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Registro = new javax.swing.JPanel();
        Inicio = new javax.swing.JButton();
        Registrarse = new javax.swing.JButton();
        RegistroG = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        atras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 100));

        Registro.setBackground(new java.awt.Color(0, 102, 102));
        Registro.setLayout(null);

        Inicio.setBackground(new java.awt.Color(51, 255, 51));
        Inicio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Inicio.setText("Iniciar sesión");
        Inicio.setMaximumSize(new java.awt.Dimension(103, 33));
        Inicio.setPreferredSize(new java.awt.Dimension(103, 33));
        Inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InicioMouseClicked(evt);
            }
        });
        Inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioActionPerformed(evt);
            }
        });
        Registro.add(Inicio);
        Inicio.setBounds(600, 310, 149, 42);

        Registrarse.setBackground(new java.awt.Color(51, 255, 51));
        Registrarse.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Registrarse.setText("Registrarse");
        Registrarse.setMaximumSize(new java.awt.Dimension(103, 33));
        Registrarse.setPreferredSize(new java.awt.Dimension(103, 33));
        Registrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistrarseMouseClicked(evt);
            }
        });
        Registro.add(Registrarse);
        Registrarse.setBounds(590, 400, 163, 42);

        RegistroG.setBackground(new java.awt.Color(51, 255, 51));
        RegistroG.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        RegistroG.setText("Registrar con Gmail");
        RegistroG.setMaximumSize(new java.awt.Dimension(103, 33));
        RegistroG.setPreferredSize(new java.awt.Dimension(103, 33));
        RegistroG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistroGMouseClicked(evt);
            }
        });
        Registro.add(RegistroG);
        RegistroG.setBounds(560, 480, 244, 42);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("FITNESS&HOUSE");
        Registro.add(jLabel1);
        jLabel1.setBounds(560, 20, 240, 110);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yamecanse/gym3.jpg"))); // NOI18N
        Registro.add(jLabel3);
        jLabel3.setBounds(1150, 0, 0, 0);

        atras.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        atras.setText("Atras");
        atras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atrasMouseClicked(evt);
            }
        });
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });
        Registro.add(atras);
        atras.setBounds(10, 10, 140, 32);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Registro, javax.swing.GroupLayout.PREFERRED_SIZE, 1344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Registro, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_InicioActionPerformed

    private void InicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InicioMouseClicked
       userPassword IniciarU = new userPassword();
        IniciarU.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_InicioMouseClicked

    private void RegistrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarseMouseClicked
       userPassword IniciarU = new userPassword();
        IniciarU.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistrarseMouseClicked

    private void RegistroGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistroGMouseClicked
        userPassword IniciarU = new userPassword();
        IniciarU.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_RegistroGMouseClicked

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_atrasActionPerformed

    private void atrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasMouseClicked
        Vista1 vs = new Vista1();
        vs.setVisible(true);

        this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_atrasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Inicio;
    private javax.swing.JButton Registrarse;
    private javax.swing.JPanel Registro;
    private javax.swing.JButton RegistroG;
    private javax.swing.JButton atras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
